### ISSUE TITLE
Loading interpretations fail when querying non-Chinese words

### ISSUE THREAD

**Issue by shayloyuki** [pnlpal/dictionariez#106]
The extension downloaded from Edge store can't load interpretations when quering any **non-Chinese** words **no matter using vpn or not**.

However, I can query the word normally when chlicking the plug-in icon.

Example images are shown below:

![image](https://img2023.cnblogs.com/blog/2399063/202302/2399063-20230202160913244-319982866.png)

![image](https://img2023.cnblogs.com/blog/2399063/202302/2399063-20230202160949664-274404882.png)

By the way, I wanna know how to add words and interpretations to anki by clicking any tab. Should I copy and paste them manually? Could you give **a tutorial video** about how to configure this plug-in and anki on windows? I'd appreciate it a a lot!

**Comment by revir** [comment]
It seems to be your network issue, that you don't have access to google dictionary which is of course banned in China. You need to change the English lookup source to `Bing Dict`. Otherwise I tested it on Edge, it all works for me.
<img width="451" alt="image" src="https://user-images.githubusercontent.com/3252034/216840387-9b61c7a6-2104-4bad-b9e9-5886ca12ec08.png">

**Comment by revir** [comment]
As for exporting words to Anki. Currently Dictionariez uses [Anki Web](https://ankiweb.net/decks/) to build cards. It has nothing to do with other anki apps.  I have a video tutorial here: https://www.youtube.com/watch?v=12XlGQCynsM

Feel free to reopen the issue if there is anything more I can do.
