### ISSUE TITLE
issue with using extension

### ISSUE THREAD

**Issue by uynayz** [pnlpal/dictionariez#132]
hi, im from that one review you told to make an issue here, i used this extension for a while and it worked quite fine until a few days prior (couldve been a few weeks.),
the issue is that it doesnt show defintions anymore, i am on debian (bookworm) and i use firefox, it was installed from the firefox add-on's thing.
it shows this little dot (image provided) and whenever i highlight a word it doesnt show, the "show on cats love youtube" doesnt show on youtube either, ive tried reinstalling a few times however nothing helped, all required permission are enabled. 
![image](https://github.com/pnlpal/dictionariez/assets/173627167/46e3cfe0-f51d-4b3a-a236-716d892894ae)
![image](https://github.com/pnlpal/dictionariez/assets/173627167/5ee2cdc2-c9e1-4b19-86bc-e368e93ab806)
![image](https://github.com/pnlpal/dictionariez/assets/173627167/723c5ae2-fee2-4747-bf7e-9d1342350f8b)
the extension seems to be completely gone for me for some reason.

**Comment by revir** [comment]
Aha, thank you for the feedback. it seems something has been totally off.  it occurred to me that start from v5.0.0, Dictionariez has upgraded to manifest v3 which is required by all browsers basically. Here is Firefox declaration: https://blog.mozilla.org/addons/2024/03/13/manifest-v3-manifest-v2-march-2024-update/

So I restricted the minimum version of Firefox that could install v5.0.0 of Dictionariez is v109 as it's specified [here](https://extensionworkshop.com/documentation/develop/manifest-v3-migration-guide/).  

Would you check which version of Firefox are you using? If you have a Firefox below v109, you might need to upgrade Firefox to a newer one, otherwise you have to download **Dictionariez v4.2.1** from https://addons.mozilla.org/en-US/firefox/addon/dictionaries/versions/

**Comment by uynayz** [comment]
Huh, thanks for updating! my installed version of firefox is V115
![image](https://github.com/pnlpal/dictionariez/assets/173627167/c9dc1b4b-38e0-4f5e-bb1b-5398f16b0ce4)

however i took your advice of downloading version 4.2.1 of the extension and it worked! i'm just updating so you know what happened, it works perfectly fine now.

**Comment by revir** [comment]
The newest Firefox version is v127 now, so I would recommend to upgrade Firefox as well otherwise Dictionariez might be stuck with v4.2.1 for you, and other add-ons which also upgraded to manifest v3 might not work either.

**Comment by revir** [comment]
Turns out there are many more issues with Manifest V3 on Firefox, so I rolled back to manifest v2 after V5.1.0 only on Firefox. I believe the newest version works perfectly on any firefox version now. Check it out.
